[project]
name = "video-downloader"
version = "0.1.0"
description = ""
authors = [
    {name = "G3rarrd",email = "gnwokeduko@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "yt-dlp[default] (>=2026.8.19,<2027.0.0)",
    "textual (>=8.2.8,<9.0.0)",
    "textual-dev (>=1.8.0,<2.0.0)"
]

[tool.poetry]
packages = [{include = "video_downloader", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
